"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { FormEvent } from "react";
import { useEffect, useState } from "react";
import { createRentalRequest, getMe, getProperty, Property } from "../../../../lib/api";
import { money } from "../../../../lib/mappers";
function LegacyPropertyDetails() { const { id } = useParams<{ id: string }>(); const [property,setProperty]=useState<Property|null>(null); const [error,setError]=useState(""); useEffect(()=>{if(id)getProperty(id).then(setProperty).catch(err=>setError(err instanceof Error?err.message:"Unable to load property"));},[id]); if(error)return <main className="section"><p className="form-error">{error}</p></main>; if(!property)return <main className="section"><p className="muted">Loading property…</p></main>; return <main className="section"><Link href="/properties" className="muted">← Back to properties</Link><div className="detail-grid"><div className="property-image detail-image" style={property.images?.[0]?{backgroundImage:`url(${property.images[0]})`,backgroundSize:"cover",backgroundPosition:"center"}:undefined}/><div><p className="eyebrow">{property.category?.name || "Featured home"}</p><h1 className="detail-title">{property.title}</h1><p className="hero-copy">{property.location} · {property.description}</p><div className="price detail-price"><strong>{money(property.rentAmount)}</strong><span>per month</span></div><Link href={`/login?redirect=/properties/${property.id}`} className="button">Start an application</Link></div></div></main>; }

export default function PropertyDetails() {
  const { id } = useParams<{ id: string }>(); const [property,setProperty]=useState<Property|null>(null); const [message,setMessage]=useState(""); const [duration,setDuration]=useState("12"); const [error,setError]=useState(""); const [success,setSuccess]=useState(""); const [loggedIn,setLoggedIn]=useState(false);
  useEffect(()=>{if(id)getProperty(id).then(setProperty).catch(err=>setError(err instanceof Error?err.message:"Unable to load property"));getMe().then(()=>setLoggedIn(true)).catch(()=>setLoggedIn(false));},[id]);
  const submit=async(e:FormEvent)=>{e.preventDefault();setError("");setSuccess("");try{await createRentalRequest({propertyId:id,message,durationMonths:Number(duration)});setSuccess("Rental request submitted successfully.");setMessage("");}catch(err){setError(err instanceof Error?err.message:"Unable to submit request")}};
  if(error&&!property)return <main className="section"><p className="form-error">{error}</p></main>; if(!property)return <main className="section"><p className="muted">Loading property…</p></main>;
  return <main className="section"><Link href="/properties" className="muted">← Back to properties</Link><div className="detail-grid"><div><div className="property-image detail-image" style={property.images?.[0]?{backgroundImage:`url(${property.images[0]})`,backgroundSize:"cover",backgroundPosition:"center"}:undefined}/>{property.images?.length>1&&<div style={{display:"grid",gridTemplateColumns:"repeat(2, 1fr)",gap:12,marginTop:12}}>{property.images.slice(1).map(image=><div key={image} className="property-image" style={{backgroundImage:`url(${image})`,backgroundSize:"cover",backgroundPosition:"center",height:150,borderRadius:12}}/>)}</div>}</div><div><p className="eyebrow">{property.category?.name||"Featured home"}</p><h1 className="detail-title">{property.title}</h1><p className="hero-copy">{property.location}{property.address?` · ${property.address}`:""}</p><p className="muted">{property.description}</p>{property.landlord?.name&&<div className="landlord-card"><div className="landlord-avatar">{property.landlord.name.charAt(0).toUpperCase()}</div><div><p className="eyebrow">Listed by</p><strong>{property.landlord.name}</strong><p className="muted">Property landlord</p></div></div>}<div className="price detail-price"><strong>{money(property.rentAmount)}</strong><span>per month</span></div><div className="panel" style={{marginBottom:18}}><div style={{display:"grid",gridTemplateColumns:"repeat(3, 1fr)",gap:16}}><div><strong>{property.bedrooms??"—"}</strong><p className="muted">Bedrooms</p></div><div><strong>{property.bathrooms??"—"}</strong><p className="muted">Bathrooms</p></div><div><strong>{property.areaSqft?`${property.areaSqft} ft²`:"—"}</strong><p className="muted">Area</p></div></div></div>{property.amenities?.length>0&&<div style={{marginBottom:22}}><p className="eyebrow">Amenities</p><div style={{display:"flex",flexWrap:"wrap",gap:8}}>{property.amenities.map(amenity=><span className="badge" key={amenity}>{amenity}</span>)}</div></div>}{loggedIn?<form className="panel" onSubmit={submit}><h2>Request this property</h2><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write a message to the landlord" required/><input type="number" min="1" max="60" value={duration} onChange={e=>setDuration(e.target.value)} placeholder="Duration in months"/><button className="button">Send rental request</button>{success&&<p className="success-message">{success}</p>}{error&&<p className="form-error">{error}</p>}</form>:<Link href={`/login?redirect=/properties/${property.id}`} className="button">Log in to request</Link>}</div></div></main>;
}
